name: check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    strategy:
      matrix:
        version: ['latest', 'nightly']
        os:
          - ubuntu-latest
          - macos-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' }}
    steps:
      - uses: actions/checkout@v4

      - name: install stable version on unix
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash -s ${{ matrix.version }}
          echo "$HOME/.moon/bin" >> $GITHUB_PATH  

      - name: moon version
        run: |
          moon version --all
          moonrun --version

      - name: install module dependencies
        run: |
          moon update
          moon check --deny-warn

      - name: moon check
        run: moon check --deny-warn --target native

      - name: moon info
        run: |
          moon info --target native
          git diff --exit-code

      - name: format diff
        run: |
          moon fmt
          git diff --exit-code

      - name: Set ulimit on unix
        run: |
          ulimit -s 8176

      - name: moon test
        run: |
          moon test --target native
          moon test --target native --release

      - name: moon test --doc
        run: |
          moon test --doc

  moon-json-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: check `moon.*.json` format
        shell: bash
        run: |
          _passed=0;
          for f in $(find . -type f -name "moon.*.json"); do
            if ! jq '.' $f > /dev/null; then
              echo $f;
              _passed=1;
            fi
          done
          (exit $_passed)

  typo-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      FORCE_COLOR: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: check typos
        uses: crate-ci/typos@v1.40.0
